[phases.install]
commands = ["npm ci"]

[phases.build]
commands = ["npm run build"]

[phases.start]
commands = ["npx serve -s build -l ${PORT}"]

[env]
NODE_ENV = "production"
PORT = "3000"

[services.web]
port = "${PORT}"
spa = true
